# Generated by Django 2.2.7 on 2020-01-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
    ]
